docker run -d \
-e "KONG_ROLE=data_plane" \
-e "KONG_DATABASE=off" \
-e "KONG_VITALS=off" \
-e "KONG_CLUSTER_MTLS=pki" \
-e "KONG_CLUSTER_CONTROL_PLANE=d7c265783e.in.cp0.konghq.com:443" \
-e "KONG_CLUSTER_SERVER_NAME=d7c265783e.in.cp0.konghq.com" \
-e "KONG_CLUSTER_TELEMETRY_ENDPOINT=d7c265783e.in.tp0.konghq.com:443" \
-e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=d7c265783e.in.tp0.konghq.com" \
-e "KONG_CLUSTER_CERT=-----BEGIN CERTIFICATE-----
MIICKTCCAdCgAwIBAgIBATAKBggqhkjOPQQDBDBGMUQwCQYDVQQGEwJJTjA3BgNV
BAMeMABrAG8AbgBuAGUAYwB0AC0AbABhAG0AcAAtAHAAbwBjAC0AZwBhAHQAZQB3
AGEAeTAeFw0yNTA3MjcwNTU4NDFaFw0zNTA3MjcwNTU4NDFaMEYxRDAJBgNVBAYT
AklOMDcGA1UEAx4wAGsAbwBuAG4AZQBjAHQALQBsAGEAbQBwAC0AcABvAGMALQBn
AGEAdABlAHcAYQB5MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuP7Dt4ib61GD
Xzvu8gYmexoSeAEsxP3mtZMkhve6ReqAKgG7iC5jKL3Cpy3+z+PZ3NQA+ZQRmRJa
oKurc+P6LKOBrjCBqzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIABjAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwFwYJKwYBBAGCNxQCBAoMCGNlcnRUeXBl
MCMGCSsGAQQBgjcVAgQWBBQBAQEBAQEBAQEBAQEBAQEBAQEBATAcBgkrBgEEAYI3
FQcEDzANBgUpAQEBAQIBCgIBFDATBgkrBgEEAYI3FQEEBgIEABQACjAKBggqhkjO
PQQDBANHADBEAiAB3RZjBRvICZjAMPxo1mMeRKFqJxWbN6jCuW3xaV6uXAIgaxSE
MT0X1vjWHO1PkpqjLRbm5ibaDDJ0z0DepwMq7ZI=
-----END CERTIFICATE-----" \
-e "KONG_CLUSTER_CERT_KEY=-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgomvslPtc3x9O32Rf
AwVd8rfQ8v12KbgB8q90XWbeAeCgCgYIKoZIzj0DAQehRANCAAS4/sO3iJvrUYNf
O+7yBiZ7GhJ4ASzE/ea1kySG97pF6oAqAbuILmMovcKnLf7P49nc1AD5lBGZElqg
q6tz4/os
-----END PRIVATE KEY-----" \
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
-e "KONG_KONNECT_MODE=on" \
-e "KONG_CLUSTER_DP_LABELS=type:docker-linuxdockerOS" \
-e "KONG_ROUTER_FLAVOR=expressions" \
-p 8000:8000 \
-p 8443:8443 \
kong/kong-gateway:3.11